server:
  port: 8081
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: User-Service
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MYSQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    
    
    
